#!/bin/sh
clear
#only needs to be done once, comment out to save time after the first run
g++ -c -fmodules-ts -x c++-system-header  -std=c++20 iostream algorithm numbers string vector map cmath list cassert fstream utility ostream
g++ -fmodules-ts -std=c++20 -lGL -lglut \
raytracer/Log.cpp \
raytracer/Vector3d.cpp \
raytracer/Farbe.cpp \
raytracer/Material.cpp \
raytracer/Math3d.cpp \
raytracer/Dreieck.cpp \
raytracer/SchnittEreignis.cpp \
raytracer/tinyxml2.cpp \
raytracer/Lichtquelle.cpp \
raytracer/Kamera.cpp \
raytracer/BoundingBox.cpp \
raytracer/Szene.cpp \
raytracer/FileImport.cpp \
raytracer/Main.cpp \
-o raytracer.out
